apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-app
  labels:
    app: java-maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
        - name: my-registry-key
      containers:
        - name: java-maven-app
          image: ilemona02/my-nrepo:$IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
